themoviedb:
  api_base_url: https://api.themoviedb.org/3
  api_key: e2ce8764b1f513d3c0c3d1b04ee6a181
  language: es
  backdrop_size: original
  backdrop_size_preview: w780
  poster_size: original
  poster_size_preview: w500
thetvdb:
  api_base_url: http://thetvdb.com/api
  api_key: 9B4009347F355E4F
  language: es